###
GET http://localhost:8080/auctions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxYzMxN2MxZTlkNDViMDkyMTE3OTE0MiIsIm5hbWUiOiJNdWhhbW1hZCBTYWFkIEp1dHQiLCJ1c2VybmFtZSI6Imloc2FuLmRpc3RyYW5nZXJAZ21haWwuY29tIiwidXNlcm5hbWVPckVtYWlsIjoiaWhzYW4uZGlzdHJhbmdlckBnbWFpbC5jb20iLCJyb2xlIjoyLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHakd3d1A3eTNQSjRMd1ZMSzdnRWoxVWdmakRXVnh0OFprQ2haTUdwQT1zOTYtYyIsImdvb2dsZUlkIjoiblMxemh1SlRreWdITzFaRGN0cXZVWXRZWXRvMSIsImNyZWF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsIl9fdiI6MH0sImlhdCI6MTY0MjE4MjA3MiwiZXhwIjoxNjQ1NzgyMDcyfQ.7rTFVji7QRRH5OjxThEaHTaeSf0GlMYU8vF4COHpcHY

###
GET http://localhost:8080/auctions/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxYzMxN2MxZTlkNDViMDkyMTE3OTE0MiIsIm5hbWUiOiJNdWhhbW1hZCBTYWFkIEp1dHQiLCJ1c2VybmFtZSI6Imloc2FuLmRpc3RyYW5nZXJAZ21haWwuY29tIiwidXNlcm5hbWVPckVtYWlsIjoiaWhzYW4uZGlzdHJhbmdlckBnbWFpbC5jb20iLCJyb2xlIjoyLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHakd3d1A3eTNQSjRMd1ZMSzdnRWoxVWdmakRXVnh0OFprQ2haTUdwQT1zOTYtYyIsImdvb2dsZUlkIjoiblMxemh1SlRreWdITzFaRGN0cXZVWXRZWXRvMSIsImNyZWF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsIl9fdiI6MH0sImlhdCI6MTY0MjE4MjA3MiwiZXhwIjoxNjQ1NzgyMDcyfQ.7rTFVji7QRRH5OjxThEaHTaeSf0GlMYU8vF4COHpcHY

### Participated by muhammad.saad@analytium account
GET http://localhost:8080/auctions/participated
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImF1Y3Rpb25zUGFydGljaXBhdGVkSW4iOlsiNjFlODhlYmI5NmYzNzkwMzZlMTUwMTdhIl0sIl9pZCI6IjYxZTlhMDQ1Mzc3YzcyYTI4YmE4YjgxMCIsIm5hbWUiOiJNdWhhbW1hZCBTYWFkIiwidXNlcm5hbWUiOiJtdWhhbW1hZC5zYWFkQGFuYWx5dGl1bS5jby51ayIsInVzZXJuYW1lT3JFbWFpbCI6Im11aGFtbWFkLnNhYWRAYW5hbHl0aXVtLmNvLnVrIiwicm9sZSI6MCwiYXZhdGFyIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2dkZFM1MEdTRGFxcmNWUUxMSnlxNk5FbVlOWkxIUnNsdDFCYk9WPXM5Ni1jIiwiZ29vZ2xlSWQiOiJsMVZTeFZOSGRzT2FhMDl5bHVJcnlSYk5kWjMzIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0yMFQxNzo0Nzo0OS43MzJaIiwidXBkYXRlZEF0IjoiMjAyMi0wMS0yMVQyMToxOTo1NS4wMjhaIiwiX192IjoyfSwiaWF0IjoxNjQyODAzNjk2LCJleHAiOjE2NDY0MDM2OTZ9.k3FFSwnfOStkrDambkukT9JuvA134ObY6pmIEU6nYGQ

###
GET http://localhost:8080/auctions/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxYzMxN2MxZTlkNDViMDkyMTE3OTE0MiIsIm5hbWUiOiJNdWhhbW1hZCBTYWFkIEp1dHQiLCJ1c2VybmFtZSI6Imloc2FuLmRpc3RyYW5nZXJAZ21haWwuY29tIiwidXNlcm5hbWVPckVtYWlsIjoiaWhzYW4uZGlzdHJhbmdlckBnbWFpbC5jb20iLCJyb2xlIjoyLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHakd3d1A3eTNQSjRMd1ZMSzdnRWoxVWdmakRXVnh0OFprQ2haTUdwQT1zOTYtYyIsImdvb2dsZUlkIjoiblMxemh1SlRreWdITzFaRGN0cXZVWXRZWXRvMSIsImNyZWF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsIl9fdiI6MH0sImlhdCI6MTY0MjE4MjA3MiwiZXhwIjoxNjQ1NzgyMDcyfQ.7rTFVji7QRRH5OjxThEaHTaeSf0GlMYU8vF4COHpcHY

###
POST http://localhost:8080/auctions/5/bid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxYzMxN2MxZTlkNDViMDkyMTE3OTE0MiIsIm5hbWUiOiJNdWhhbW1hZCBTYWFkIEp1dHQiLCJ1c2VybmFtZSI6Imloc2FuLmRpc3RyYW5nZXJAZ21haWwuY29tIiwidXNlcm5hbWVPckVtYWlsIjoiaWhzYW4uZGlzdHJhbmdlckBnbWFpbC5jb20iLCJyb2xlIjoyLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHakd3d1A3eTNQSjRMd1ZMSzdnRWoxVWdmakRXVnh0OFprQ2haTUdwQT1zOTYtYyIsImdvb2dsZUlkIjoiblMxemh1SlRreWdITzFaRGN0cXZVWXRZWXRvMSIsImNyZWF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsIl9fdiI6MH0sImlhdCI6MTY0MjE4MjA3MiwiZXhwIjoxNjQ1NzgyMDcyfQ.7rTFVji7QRRH5OjxThEaHTaeSf0GlMYU8vF4COHpcHY
content-type: application/json

{
    "bidAmount": "134"
}
###
DELETE http://localhost:8080/auctions/61d87851b631cbdbce5777eb

###
POST http://localhost:8080/auctions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxYzMxN2MxZTlkNDViMDkyMTE3OTE0MiIsIm5hbWUiOiJNdWhhbW1hZCBTYWFkIEp1dHQiLCJ1c2VybmFtZSI6Imloc2FuLmRpc3RyYW5nZXJAZ21haWwuY29tIiwidXNlcm5hbWVPckVtYWlsIjoiaWhzYW4uZGlzdHJhbmdlckBnbWFpbC5jb20iLCJyb2xlIjoyLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHakd3d1A3eTNQSjRMd1ZMSzdnRWoxVWdmakRXVnh0OFprQ2haTUdwQT1zOTYtYyIsImdvb2dsZUlkIjoiblMxemh1SlRreWdITzFaRGN0cXZVWXRZWXRvMSIsImNyZWF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMjJUMTI6MTk6MTMuMjYyWiIsIl9fdiI6MH0sImlhdCI6MTY0MjE4MjA3MiwiZXhwIjoxNjQ1NzgyMDcyfQ.7rTFVji7QRRH5OjxThEaHTaeSf0GlMYU8vF4COHpcHY
content-type: application/json

{
    "offerId": "offerId2",
    "expirationTime": 1642268520000,
    "startingBid": "123"
}

###
POST http://localhost:8080/auctions
content-type: application/json

{
    "value": "new todo 3"
}